# Generated by Django 5.1.1 on 2024-09-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_choice_choice1_choice2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice1',
            new_name='Choice',
        ),
        migrations.DeleteModel(
            name='Choice2',
        ),
    ]
